"""initial_schema

Revision ID: ced523bcf5dd
Revises: 
Create Date: 2026-04-23 22:44:47.810839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'ced523bcf5dd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('plan_type', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('permission_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_org_created', 'users', ['organization_id', 'created_at'], unique=False)
    op.create_table('meetings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('media_type', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_meetings_org_created', 'meetings', ['organization_id', 'created_at'], unique=False)
    op.create_table('action_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_action_items_org_created', 'action_items', ['organization_id', 'created_at'], unique=False)
    op.execute("CREATE INDEX ON action_items USING hnsw (embedding vector_cosine_ops)")
    op.create_table('meeting_access',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permission_level', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('speakers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('speaker_label', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_speakers_org_created', 'speakers', ['organization_id', 'created_at'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('short_summary', sa.Text(), nullable=True),
    sa.Column('detailed_summary', sa.Text(), nullable=True),
    sa.Column('summary_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_summaries_org_created', 'summaries', ['organization_id', 'created_at'], unique=False)
    op.execute("CREATE INDEX ON summaries USING hnsw (summary_embedding vector_cosine_ops)")
    op.create_table('transcript_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('speaker_id', sa.UUID(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=True),
    sa.Column('timestamp_start', sa.Float(), nullable=True),
    sa.Column('timestamp_end', sa.Float(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('tsvector_col', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['speaker_id'], ['speakers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunks_org_created', 'transcript_chunks', ['organization_id', 'created_at'], unique=False)
    op.execute("CREATE INDEX ON transcript_chunks USING hnsw (embedding vector_cosine_ops)")
    op.execute("CREATE INDEX idx_transcript_chunks_tsvector ON transcript_chunks USING GIN (tsvector_col)")
    op.execute("""
CREATE FUNCTION update_tsvector() RETURNS trigger AS $$
BEGIN
  NEW.tsvector_col := to_tsvector('english', coalesce(NEW.chunk_text, ''));
  RETURN NEW;
END
$$ LANGUAGE plpgsql;
    """)
    op.execute("""
CREATE TRIGGER tsvector_update BEFORE INSERT OR UPDATE
ON transcript_chunks FOR EACH ROW EXECUTE PROCEDURE update_tsvector();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS tsvector_update ON transcript_chunks;")
    op.execute("DROP FUNCTION IF EXISTS update_tsvector();")
    op.execute("DROP INDEX IF EXISTS idx_transcript_chunks_tsvector;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_org_created', table_name='transcript_chunks')
    op.drop_table('transcript_chunks')
    op.drop_index('ix_summaries_org_created', table_name='summaries')
    op.drop_table('summaries')
    op.drop_index('ix_speakers_org_created', table_name='speakers')
    op.drop_table('speakers')
    op.drop_table('meeting_access')
    op.drop_index('ix_action_items_org_created', table_name='action_items')
    op.drop_table('action_items')
    op.drop_index('ix_meetings_org_created', table_name='meetings')
    op.drop_table('meetings')
    op.drop_index('ix_users_org_created', table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    op.drop_table('organizations')
    # ### end Alembic commands ###
